language: node_js
node_js: node
before_deploy:
 git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: df9bd3c0-0be0-4809-9a3a-de809d4805f3
  app: shrouded-anchorage-29615
  on:
    repo: lightsage88/mobius
