language: node_js
node_js: node
before_deploy:
 git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: 8aec391c-5a4e-4f3e-88ae-9925f7dd93b6
  app: shrouded-anchorage-29615
  on:
    repo: lightsage88/mobius
