language: node_js
node_js: node
before_deploy:
 git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: 1d3439cc-0634-4b97-be9a-a3e053b03b76
  app: shrouded-anchorage-29615
  on:
    repo: lightsage88/mobius
