language: node_js
node_js: node
before_deploy:
 git config --global alias.stash 'stash -q'
deploy:
  provider: heroku
  api_key:
    secure: aae00a1b-2776-4cac-905a-eb9c75282c65
  app: shrouded-anchorage-29615
  on:
    repo: lightsage88/mobius
