language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: u1/61h2xUFHkVKF3Np6QG76hNuuSCZMlfxevdmbyTYQG2n61HqIvThDf39gZ33cA1krhTT6BXevXvGcxixahJwsbi4eqfPngcL9PRrTyafEXXQ2/+qEHHGfC3zIdu3xVv/7wK12Z4HJ0Cy4pu9zy4qLIlmKO9ROr0Hgsft0Kh02ZKNtrckeuOQVzppZYx69M0KvXywtfZ0XcvIrTiztGfS57K7SIrlZXuEQ2KmZM5NMhlxkJSw1RKEc7NmH05Ur+NYW2OggS83scxXfLmN22SUUtiM+O3wMiVXuCeHcEEOp640GFC2oLehE0TTjxaeaCEjTQPnYZtgoQ7ztrmiTTE7euuW34C6HI21dJ/KXBeNaJIKXEgl+Zv45/aIr9NWLYmkZtDoYxj7nhGSeXhZcnCp2DWkqUVMXWV0/3q3A1IGmsDeUGt6IF6CYBM1zQIMMzSjnoRssWnJb93TIupw1+OC5PDHzUz5K1CNLpmP+NkYaEtJt5GJK6h6dPulSfkEStPcJbnKEbOSOdWvoOmfe4/3SySwxM+MWxQA1SXFpBeX3eXM0nmFdo5QzzCdfZ0KER56wYatmOCpPTfRvR3V+2PzkO6tOQY84x1fJUmn9DtpRG34gsz0JGxz2l1Vehb7Bq/w6NTaRLSAnrVoTQ/gjIXBLToAK6cL8oidzaQecLhsA=
  app: mobius
  on:
    repo: lightsage88/mobius
